### PR TITLE
Return object if desired instead of response and multiply 100 the amo…

### PR DESCRIPTION
**Pull request by ebisbe**
…unt instead of having to depend on the user to do that.

### CODE REVIEW

**Comment by jsampedro77** [comment]
Hi Eric,

It's been a long time since I last used this lib, so I was not aware of the new callback.
If it's working for you, I am ok with merging it.

However the multiplication of the amount should be removed from this PR, as it would break compatibility.

**Comment by ebisbe** [comment]
@jsampedro77 I've made a work arround because I think that the multiplication should be made by the bundle because it's a requirement from Redsys.

**Comment by jsampedro77** [comment]
@ebisbe It's quite common to use money data with integer, in order to avoid php's float point operations.
So this multiplication has to be done on the client side only when you are working with decimal money.

Furthermore, this change would imply modifiyng the client code in applications that are already using it, causing a back compatibility break.

**Comment by ebisbe** [comment]
@jsampedro77 I've made a change to the getAmount() function. Have you check it?

**Comment by jsampedro77** [comment]
@ebisbe Ooops, no, I hadn't seen  the new commit.

Merging, thanks!

**Pull request merged**
